classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.ubuntu
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- cluster.mcp-day01.infra
- cluster.mcp-day01.infra.maas
- cluster.mcp-day01.infra.jenkins
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/Mirantis/mcp-drivetrain-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$lGeSiPvI$Gsul5ejaLB41ITn3G56QrgM0qZMW4zXgKc.oSGn.AJLc4Salx/XMBewQYwGkdHc6.ZQvPRQNeGByzYX8kdGae/"
    salt_api_password: Ll7yvUFrd1xWe71RT4m9EmznrUPkqw6c
    salt_master_host: ${_param:infra_config_deploy_address}
  linux:
    network:
      interface:
        ens3:
          enabled: true
          type: eth
          proto: dhcp
  salt:
    minion:
      master:
        host: "localhost"
  reclass:
    storage:
      data_source:
        engine: local

