classes:
- system.linux.system.single.debian
#- system.openssh.server.team.cicd
parameters:
  _param:
    # TODO: Uncomment next line "linux_system_user_sudo: true" during the deployment.
    # Don't set it "false" before you configure sudo policies and enable power users.
    # linux_system_user_sudo: true
    apt_mk_version: "2018.3.1"
    linux_repo_refresh_db: true
    infra_config_hostname: cfg01
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    # infra service addresses
    infra_config_address: 127.0.0.1
    infra_config_deploy_address: 127.0.0.1
    cluster_domain: mcp-day01.local
    cluster_name: mcp-day01
    dns_server01: 8.8.8.8
  salt:
    minion:
      trusted_ca_minions:
        - ${_param:salt_minion_ca_host}
  linux:
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      purge_repos: True
      service:
        apt-daily.timer:
          status: dead
      user:
        root:
          password: false
